version: "2.4"
services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/srv/app:cached
      - /srv/app/persistent
    command: tail -f /dev/null
    depends_on:
      - db

  db:
    image: postgres:11.5
    volumes:
      - ./persistent/pgdata:/var/lib/postgresql/data/pgdata:cached
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
