version: '3.7'
services:
  db:
    image: postgres:11.5
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /srv/data/postgres:/var/lib/postgresql/data/pgdata

  blog:
    deploy:
      placement:
        constraints: [node.role == manager]
    secrets:
      - source: master_key
        target: /srv/app/config/master.key
    image: registry.gitlab.com/swarm-workshop/blog/production:latest
    environment:
      - RAILS_MAX_THREADS=5
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true

  gateway:
    deploy:
      placement:
        constraints: [node.role == manager]
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - /srv/deployment/nginx.conf:/etc/nginx/conf.d/default.conf

secrets:
  master_key:
    external: true
